from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Packet(Base):
    __tablename__ = "packet"
    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(Float)
    frame_time_delta = Column(Float)
    frame_time_epoch = Column(Float)
    frame_number = Column(Integer)
    frame_len = Column(Float)
    radiotap_datarate = Column(Float)
    radiotap_dbm_antsignal = Column(Float)
    radiotap_channel_freq = Column(Float)
    # radiotap_length = Column(Float)
    # radiotap_rxflags = Column(Float)
    radiotap_mactime = Column(Float)
    wlan_duration = Column(Float)
    wlan_fc_type = Column(Integer)
    wlan_fc_subtype = Column(Integer)
    # wlan_fc_retry = Column(Integer)
    # wlan_fc_ds = Column(Integer)
    # wlan_fc_protected = Column(Integer)
    # wlan_fc_pwrmgt = Column(Integer)
    # wlan_fc_order = Column(Integer)
    # wlan_fc_frag = Column(Integer)
    # wlan_fixed_reason_code = Column(Integer)
    # wlan_seq = Column(Integer)
    wlan_bssid = Column(String)
    wlan_sa = Column(String)
    wlan_da = Column(String)
    # ip_src = Column(String)
    # ip_dst = Column(String)
    # ip_proto = Column(String)
    # tcp_srcport = Column(Integer)
    # tcp_dstport = Column(Integer)
    # udp_srcport = Column(Integer)
    # udp_dstport = Column(Integer)
    # arp_opcode = Column(Integer)
    # arp_src_proto_ipv4 = Column(String)
    # arp_dst_proto_ipv4 = Column(String)
    label = Column(Integer, nullable=False)
    proba_attack = Column(Float, nullable=False)
    attack_type = Column(String)
